name: Build Comicazen Only
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build APK Khusus Comicazen
        run: |
          chmod +x gradlew
          ./gradlew :src:id:comicazen:assembleRelease

      - name: Upload APK Ke Sini
        uses: actions/upload-artifact@v4
        with:
          name: Comicazen-APK
          path: src/id/comicazen/build/outputs/apk/release/*.apk
